### ISSUE TITLE
Create tag overview page

### ISSUE THREAD

**Issue by SethBarberee** [SethBarberee/sethbarberee.github.io#16]
List all tags and have a description to them.

I like how Xe did it here.
https://xeiaso.net/blog/series

**Comment by SethBarberee** [comment]
Probably do something like datafiles -> https://jekyllrb.com/docs/datafiles/

i.e.
In `_data/tags.yml`
```yaml

-  name: nvim
   description: neovim stuff

-  name: pmd-red
   description: writings about Pokemon Mystery Dungeon: Red Rescue Team 

```

```html

<ul>
{% for tag in site.data.tags %}
  <li>
    <a {{ tag.name }}  - {{ tag.description }} </a>
  </li>
{% endfor %}
</ul>

```

TODO: what happens when a tag isn't listed here..
