### ISSUE TITLE
Create convo include

### ISSUE THREAD

**Issue by SethBarberee** [SethBarberee/sethbarberee.github.io#18]
```html
<div class = "convo">
<p> Seth: This is a test for convo/coloring.<\p>

</div>
<p></p> <!-- Mainly to create a line break. TODO: Do I need this? -->
```

```css
.convo {
    background: var(--bg-secondary);
}
```

Need to test this more but looked decent. Need someone with a better eye to let me know how it looks.
