### ISSUE TITLE
Add Bike Map to Website

### ISSUE THREAD

**Issue by SethBarberee** [SethBarberee/sethbarberee.github.io#19]
- [ ] Add action to pull data from Strava API
- [x] Strip data of only Bike Data
- [x] Add page to website displaying the data
- [x] Add title to bike page
- [ ] Update website workflow to update pages when data is updated

**Comment by SethBarberee** [comment]
Github Workflow Markup using [this](https://jamesiv.es/blog/github/actions/2020/03/07/fetching-authenticated-api-data#overview) as a reference.

Cron action runs at 3:10PM daily.

```yaml
name: Refresh Bike Feed
on:
  schedule:
    - cron: 10 15 * * 0-6
jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Fetch API Data 📦
        uses: JamesIves/fetch-api-data-action@releases/v1
        with:
          TOKEN_ENDPOINT: https://www.strava.com/api/v3/oauth/token
          TOKEN_CONFIGURATION: '{ "method": "POST", "body": {"client_id": "${{ secrets.client_id }}", "client_secret": "${{ secrets.client_secret }}"} }'
          ENDPOINT: https://www.strava.com/api/v3/athlete/activities
          CONFIGURATION: '{ "method": "GET", "headers": {"Authorization": "Bearer {{{ data.access_token }}}"} }'
          SAVE_NAME: strava

      - name: Filter JSON for only runs and export back to CSV
        run:  |
          <TODO>
```
